# Uso de arrays en NumPy
## Índice
- [Características de los arrays](#características-de-los-arrays)
    - [Características principales](#características-principales)
    - [Ventajas sobre las listas de Python](#ventajas-sobre-las-listas-de-python)
    - [Operaciones comunes](#operaciones-comunes)
    - [Limitación principal](#limitación-principal)
- [Creación de arrays](#creación-de-arrays)
    - [Creación a partir de colecciones](#creación-a-partir-de-colecciones)
    - [Creación desde una lista](#creación-desde-una-lista)
    - [Creación desde una tupla](#creación-desde-una-tupla)
    - [Crear arrays desde rangos de números](#crear-arrays-desde-rangos-de-números)
    - [Relleno de arrays con un mismo valor](#relleno-de-arrays-con-un-mismo-valor)
    - [Creación de arrays vacíos](#creación-de-arrays-vacíos)
    - [Creación de arrays con valores aleatorios](#creación-de-arrays-con-valores-aleatorios)
- [Acceso y modificación de elementos](#acceso-y-modificación-de-elementos)
    - [Acceder a un elemento](#acceder-a-un-elemento)
- [Tipos de datos numéricos de los arrays](#tipos-de-datos-numéricos-de-los-arrays)
    - [Tipos de datos específicos de los arrays de NumPy](#tipos-de-datos-específicos-de-los-arrays-de-numpy)
    - [Propiedad dtype](#propiedad-dtype)
    - [Tipos de datos numéricos en NumPy](#tipos-de-datos-numéricos-en-numpy)
    - [Conversión a otro tipo de dato](#conversión-a-otro-tipo-de-dato)
    - [Crear arrays con un tipo de dato específico](#crear-arrays-con-un-tipo-de-dato-específico)
- [Propiedades de los arrays](#propiedades-de-los-arrays)
    - [size](#size)
    - [ndim](#ndim)
    - [shape](#shape)
    - [itemsize](#itemsize)
    - [nbytes](#nbytes)
- [Operaciones con arrays](#operaciones-con-arrays)
    - [Operaciones de cambio de forma](#operaciones-de-cambio-de-forma)
    - [Indexaciones](#indexaciones)
    - [Indexación sofisticada](#indexación-sofisticada)
    - [Vistas y copias](#vistas-y-copias)
    - [Operaciones vectorizadas (broadcasting)](#operaciones-vectorizadas-broadcasting)
    - [Operaciones de cálculo de totales](#operaciones-de-cálculo-de-totales)
    - [Otras operaciones útiles](#otras-operaciones-útiles)

La línea de código siguiente importa la librería NumPy y la asigna al alias **np**, que es el alias convencionalmente utilizado en la comunidad científica de Python. Esto permite acceder a las funciones y clases de NumPy utilizando el prefijo **np.**
Es imprescindible ejecutar esta línea para poder ejecutar cualquiera de las celdas de código de este cuaderno.

In [ ]:
import numpy as np # Siempre hay que ejecutar este código antes de poder ejecutar el resto de celdas

# Creación de arrays

## Creación a partir de colecciones

### Creación desde una lista

### Creación desde una tupla

Los datos deben de ser homogéneos. Si hay arrays y strings combinados, todos los datos se convierten a strings

In [6]:
a = np.arange(1,10)
print(a)

b = np.arange(1,10,2)
print(b)

c = np.arange(10,1,-1)
print(c)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2]


In [19]:
a = np.linspace(1,10,3)
print(a) # 3 valores entre 1 y 10 separados por la misma cantidad

b = np.linspace(1,101,51)
print(b) # 51 valores entre 1 y 101 separados por la misma cantidad

[ 1.   5.5 10. ]
[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.  21.  23.  25.  27.
  29.  31.  33.  35.  37.  39.  41.  43.  45.  47.  49.  51.  53.  55.
  57.  59.  61.  63.  65.  67.  69.  71.  73.  75.  77.  79.  81.  83.
  85.  87.  89.  91.  93.  95.  97.  99. 101.]


In [ ]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
a = np.full(5,6) # 5 seises
print(a)

[6 6 6 6 6]


In [20]:
a = np.zeros((3,4)) # Array de 3 filas y 4 columnas relleno de ceros
print(a)

b = np.full((2,5),9) # Array de 2 filas y 5 columnas relleno de nueves
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[9 9 9 9 9]
 [9 9 9 9 9]]


In [4]:
a = np.empty(5)
print(a) # Es impredecible lo que contiene el array a

[ 1.    2.75  6.   10.75 17.  ]


In [8]:
a = np.random.randint(1,10,5) # 5 valores enteros aleatorios entre 1 y 9
print(a)
a = np.random.randint(1,100,(3,4)) # Array de 3 filas y 4 columnas con valores entre 1 y 99
print(a)

[1 8 2 2 4]
[[80 90 36 74]
 [67 62 40 74]
 [11 35 80 55]]


In [16]:
a = np.random.random(5) # 5 valores decimales aleatorios entre 0 y 1
print(a)
a = np.random.random((2,3)) # Array de 2 filas y 3 columnas con valores entre 0 y 1
print(a)

[0.84453385 0.74732011 0.53969213 0.58675117 0.96525531]
[[0.60703425 0.27599918 0.29627351]
 [0.16526694 0.01563641 0.42340148]]


In [6]:
a = np.random.standard_normal(5) # 5 valores decimales aleatorios con distribución normal estándar
print(a)
a = np.random.standard_normal((2,3)) # Array de 2 filas y 3 columnas con valores con distribución normal estándar
print(a)

[-1.05683555  0.53269907  1.68188475  1.05290483  1.57430606]
[[-2.08348299 -0.49540658 -0.46915604]
 [-0.90232818 -0.05155832  0.9624893 ]]


### Cambio de la semilla
El módulo random permite establecer una semilla para el generador de números aleatorios. La semilla es el valor inicial que se utiliza para generar la secuencia de números aleatorios. Si se establece la misma semilla, se obtendrá la misma secuencia de números aleatorios cada vez que se ejecute el código.
El método **seed** permite establecer la semilla.

Se recomienda actualmente usar el objeto Generator para generar números aleatorios, ya que ofrece mejores prestaciones y más funcionalidades.
Para ello se utiliza el método **default_rng** que crea un generador de números aleatorios.
Los generadores aportan métodos para crear arrays con diferentes distribuciones de probabilidad.

# Acceso y modificación de elementos

## Acceder a un elemento
Se puede acceder utilizando índices, empezando por 0. El índice se usa entre corchetes []. Para arrays multidimensionales, se usan comas para separar los índices de cada dimensión.

Los arrays son mutables, podemos cambiar el valor de los elementos

Acceso a elementos en arrays multidimensionales

Podemos usar valores negativos en los índices para contar desde el final

# Tipos de datos numéricos de los arrays
## Tipos de datos específicos de los arrays de NumPy
- Hay que tener en cuenta que lo que se pretende de esta librería es precisión y velocidad
- Los tipos numéricos existentes en Python (**integer** y **float**) son demasiado genéricos, especialmente en el caso de integer.
- NumPy usa tipos mucho más especializados
- Son más parecidos a los que utilizan lenguajes de alto rendimiento como por ejemplo **C**.
- Son mucho más eficientes

## Propiedad dtype
Cada array tiene una propiedad llamada **dtype** que indica el tipo de datos de sus elementos

m## Tipos de datos numéricos en NumPy
### Enteros
| **Tipo**   | **Valores**                                                  | **Rango**        |
| ---------- | ------------------------------------------------------------ | ---------------- |
| **bool**   | Solo  True o False. Ocupa 1 bit                              | True  o False    |
| **int**    | Entero  por defecto en el sistema (pueden ser int32 o int64) | ...              |
| **int8**   | Enteros  pequeños de un byte                                 | -128  a 127      |
| **int16**  | Enteros  de dos bytes                                        | -32768  a 32767  |
| **int32**  | Enteros  de 4 bytes                                          | de  -231 a 231-1 |
| **int64**  | Enteros  de 8 bytes                                          | de  -263 a 263-1 |
| **uint8**  | Enteros  positivos de 1 byte                                 | 0  a 255         |
| **uint16** | Enteros  positivos de 2 bytes                                | 0  a 65535       |
| **uint32** | Enteros  positivos de 4 bytes                                | 0  a a 232-1     |
| **uint64** | Enteros  positivos de 8 bytes                                | 0  a a 264-1     |

### Decimales de coma flotante
| **Tipo**      | **Valores**                                    |
| ------------- | ---------------------------------------------- |
| **float**     | Decimal  de coma flotante genérico. Es float64 |
| **float16**   | Números  decimales de coma flotante de 2 bytes |
| **float32**   | Números  decimales de coma flotante de 4 bytes |
| **float63**   | Números  decimales de coma flotante de 8 bytes |
| **complex**   | Números  complejos genéricos. Es complex128    |
| **complex64** | Número  complejo formado por dos float32       |
| **complex64** | Número  complejo formado por dos float64       |

In [26]:
x = np.array([19, 25])
print(np.float64(x))

[19. 25.]


In [27]:
array = np.array([1,2,3], dtype="float64")
print(array)

[1. 2. 3.]


In [28]:
a = np.arange(1,11)
b = np.array([[2, 3, 4],[5, 6, 7]])
print(a.size) # Escribe 10
print(b.size) # aunque tiene dos dimensiones cuenta elementos (6)


10
6


In [29]:
a = np.arange(1,11)
b = np.array([[2, 3, 4],[5, 6, 7]])
print(a.ndim) # Escribe 1
print(b.ndim) # Escribe 2, dos dimensiones

1
2


In [30]:
a = np.arange(1,11)
b = np.array([[2, 3, 4],[5, 6, 7]])
print(a.shape) # Escribe (10,)
print(b.shape) # Escribe (2,3)


(10,)
(2, 3)


In [33]:
a = np.random.randint(1,10,100, dtype="int64") # Array de 100 elementos con valores entre 1 y 10
print(a.itemsize) # Cada elemento ocupa 8 bytes (int64)
print(a.nbytes) # Como hay 100 elementos, ocupa 800 bytes


8
800


In [36]:
a = np.array([[2, 3, 4],[5, 6, 7]])
a2 = a.reshape(6)
print(a2)

[2 3 4 5 6 7]


In [38]:
a = np.array([[2, 3, 4],[5, 6, 7]])
a2 = a.flatten()
print(a2)
# Este código es equivalente
a2 = a.reshape(a.size)
print(a2)

[2 3 4 5 6 7]
[2 3 4 5 6 7]


In [39]:
a = np.array([[2, 3, 4],[5, 6, 7]])
a2 = a.ravel()
print(a2)

[2 3 4 5 6 7]


In [40]:
a = np.array([[2, 3, 4],[5, 6, 7]])
a2 = a.transpose()
print(a2)

[[2 5]
 [3 6]
 [4 7]]


In [46]:
a = np.arange(1,11)
print("array original (a) ->",a)
print("a[2:5] ->",a[2:5])
print("a[:5] ->",a[:5])
print("a[2:] ->",a[2:])
print("a[2:7:2] ->",a[2:7:2])
print("a[::-1] ->",a[::-1])
print("a[-3:] ->",a[-3:])


array original (a) -> [ 1  2  3  4  5  6  7  8  9 10]
a[2:5] -> [3 4 5]
a[:5] -> [1 2 3 4 5]
a[2:] -> [ 3  4  5  6  7  8  9 10]
a[2:7:2] -> [3 5 7]
a[::-1] -> [10  9  8  7  6  5  4  3  2  1]
a[-3:] -> [ 8  9 10]


In [51]:
b= np.arange(1,13).reshape(4,3) # Array de 4 filas y 3 columnas
print("Array b original \n",b)
print("b[1] \n",b[1]) # Toma la segunda fila
print("b[:,1]\n",b[:,1]) # Toma la segunda columna
print("b[1,:2]\n",b[1,:2]) # Toma los dos primeros elementos de la segunda fila
print("b[:2,:2]\n",b[:2,:2]) # 2 primeras filas y columnas

Array b original 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b[1] 
 [4 5 6]
b[:,1]
 [ 2  5  8 11]
b[1,:2]
 [4 5]
b[:2,:2]
 [[1 2]
 [4 5]]


In [55]:
a = np.arange(1,11)
print("a>5 -> ",a>5) # Devuelve un array de booleanos con valores
            # True para los mayores de 5 y False para los menores o iguales

a>5 ->  [False False False False False  True  True  True  True  True]


In [56]:
print("a[a>5] -> ",a[a>5])

a[a>5] ->  [ 6  7  8  9 10]


In [60]:
a = np.arange(1,21).reshape(5,4)
print("Array a original \n",a)
indices =  [1,2]
print("Array usando índices [1,2]\n",a[indices])

Array a original 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
Array usando índices [1,2]
 [[ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a  = np.arange(1,13).reshape(4,3)
print("Array original, a:\n",a)
vista = a[:2,1:3] # Vista de las dos primeras filas y dos últimas columnas
print("Vista :\n",vista)
vista[0,0] = 99 # Modificamos un elemento de la vista
print("Array original modificado \n",a) # El array original también se ha modificado

Array original, a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vista :
 [[2 3]
 [5 6]]
Array original modificado 
 [[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
a  = np.arange(1,13).reshape(4,3)
print("Array original, a:\n",a)
copia = a[:2,1:3].copy() # Copia de las dos primeras filas y dos últimas columnas
print("Copia :\n",copia)
copia[0,0] = 88 # Modificamos un elemento de la copia
print("Array original tras modificar la copia \n",a) # El array original no se ha modificado

Array original, a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Copia :
 [[2 3]
 [5 6]]
Array original tras modificar la copia 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
a = np.arange(10,70,10).reshape(2,3)
print("Array original, a:\n",a)
b = np.arange(5,35,5).reshape(2,3)
print("Array original, b:\n",b)
# Operaciones
print("Suma a + b:\n",a + b)
print("Resta a - b:\n",a - b)
print("Multiplicación a * b:\n",a * b)
print("División a / b:\n",a / b)
print("Resto a % b:\n",a % b)

Array original, a:
 [[10 20 30]
 [40 50 60]]
Array original, b:
 [[ 5 10 15]
 [20 25 30]]
Suma a + b:
 [[15 30 45]
 [60 75 90]]
Resta a - b:
 [[ 5 10 15]
 [20 25 30]]
Multiplicación a * b:
 [[  50  200  450]
 [ 800 1250 1800]]
División a / b:
 [[2. 2. 2.]
 [2. 2. 2.]]
Resto a % b:
 [[0 0 0]
 [0 0 0]]


In [15]:
b = a + 3
print("Array 'b' tras b = a + 3:\n",b)
b = a * 2
print("Array 'b' tras b = a * 2:\n",b)

Array 'b' tras b = a + 3:
 [[ 35  55  75]
 [ 95 115 135]]
Array 'b' tras b = a * 2:
 [[ 64 104 144]
 [184 224 264]]


In [14]:
a += 3
print("Array 'a' tras a += 3:\n",a)
a *= 2
print("Array 'a' tras a *= 2:\n",a)

Array 'a' tras a += 3:
 [[16 26 36]
 [46 56 66]]
Array 'a' tras a *= 2:
 [[ 32  52  72]
 [ 92 112 132]]


In [21]:
a = np.arange(1,13).reshape(3,4)
print("Array original, a:\n",a)
print("Raíz cuadrada de a:\n",np.sqrt(a))
print("Exponencial de a:\n",np.exp(a))
print("Logaritmo natural de a:\n",np.log(a))
print("Seno de a:\n",np.sin(a))
print("Coseno de a:\n",np.cos(a))
print("Tangente de a:\n",np.tan(a))

Array original, a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Raíz cuadrada de a:
 [[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]
Exponencial de a:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]]
Logaritmo natural de a:
 [[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]]
Seno de a:
 [[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]
 [ 0.41211849 -0.54402111 -0.99999021 -0.53657292]]
Coseno de a:
 [[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003]
 [-0.91113026 -0.83907153  0.0044257   0.84385396]]
Tangente de a:
 [[ 1.55740772e+00 -2.18503986e+00 -1.42546543

In [17]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Array original, a:\n",a)
print("Suma total de todos los elementos:\n", np.sum(a))
print("Media de todos los elementos:\n", np.mean(a))
print("Valor mínimo:\n", np.min(a))
print("Valor máximo:\n", np.max(a))
print("Desviación estándar:\n", np.std(a))
print("Mediana:\n", np.median(a))
print("Percentil 25:\n", np.percentile(a, 25))
print("Todos los valores verdaderos en a > 50:\n", np.all(a > 50))
print("Algún valor verdadero en a > 50:\n", np.any(a > 50))

Array original, a:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Suma total de todos los elementos:
 450
Media de todos los elementos:
 50.0
Valor mínimo:
 10
Valor máximo:
 90
Desviación estándar:
 25.81988897471611
Mediana:
 50.0
Percentil 25:
 30.0
Todos los valores verdaderos en a > 50:
 False
Algún valor verdadero en a > 50:
 True


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print("Array concatenado c:\n",c)

Array concatenado c:
 [1 2 3 4 5 6]


In [20]:
a= np.arange(1,7).reshape(2,3)
print("Array original, a:\n",a)
b= np.arange(7,10).reshape(1,3)
print("Array original, b:\n",b)
print("Concatenación de a y b:\n",np.concatenate((a,b)))

Array original, a:
 [[1 2 3]
 [4 5 6]]
Array original, b:
 [[7 8 9]]
Concatenación de a y b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
a= np.arange(1,7).reshape(2,3)
print("Array original, a:\n",a)
b = np.array([10,20,30])
print("Array original, b:\n",b)
print("Array apilado con vstack:\n",np.vstack([a,b]))

Array original, a:
 [[1 2 3]
 [4 5 6]]
Array original, b:
 [10 20 30]
Array apilado con vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [22]:
a= np.arange(1,7).reshape(2,3)
print("Array original, a:\n",a)
b = np.array([[10],[20]])
print("Array original, b:\n",b)
print("Array apilado con hstack:\n",np.hstack([a,b]))

Array original, a:
 [[1 2 3]
 [4 5 6]]
Array original, b:
 [[10]
 [20]]
Array apilado con hstack:
 [[ 1  2  3 10]
 [ 4  5  6 20]]


In [24]:
a = np.arange(1,10)
print("Array original, a:\n",a)
print("Arrays resultantes del troceado:\n",np.split(a,[3,5]))


Array original, a:
 [1 2 3 4 5 6 7 8 9]
Arrays resultantes del troceado:
 [array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]


In [26]:
a = np.arange(1,10)
print("Array original, a:\n",a)
x, y, z = np.split(a,[3,5])
print("X ->",x)
print("Y ->",y)
print("Z ->",z)

Array original, a:
 [1 2 3 4 5 6 7 8 9]
X -> [1 2 3]
Y -> [4 5]
Z -> [6 7 8 9]


In [27]:
a = np.arange(1,13).reshape(3,4)
print("Array original, a:\n",a)
x,y = np.vsplit(a,[2]) # Divide en dos arrays, el primero con las dos primeras filas
print("x:\n",x)
print("Yy:\n",y)

Array original, a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x:
 [[1 2 3 4]
 [5 6 7 8]]
Yy:
 [[ 9 10 11 12]]


In [28]:
a = np.arange(1,13).reshape(3,4)
print("Array original, a:\n",a)
x,y = np.hsplit(a,[2]) # Divide en dos arrays, el primero con las dos primeras columnas
print("x:\n",x)

Array original, a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [29]:
a = np.array([10,20,30,40,50])
b = np.array([30,40,50,60,70])
print("Array a:\n",a)
print("Array b:\n",b)
print("Unión de a y b:\n",np.union1d(a,b))
print("Intersección de a y b:\n",np.intersect1d(a,b))
print("Diferencia de a y b (elementos en a no en b):\n",np.setdiff1d(a,b))
print("Operación xor simétrica (elementos en a o b pero no en ambos):\n",np.setxor1d(a,b))

Array a:
 [10 20 30 40 50]
Array b:
 [30 40 50 60 70]
Unión de a y b:
 [10 20 30 40 50 60 70]
Intersección de a y b:
 [30 40 50]
Diferencia de a y b (elementos en a no en b):
 [10 20]
Operación xor simétrica (elementos en a o b pero no en ambos):
 [10 20 60 70]


In [30]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[3,4],[5,6],[7,8]])
print("Array a:\n",a)
print("Array b:\n",b)
print("Unión de a y b:\n",np.union1d(a,b))
print("Intersección de a y b:\n",np.intersect1d(a,b))
print("Diferencia de a y b (filas en a no en b):\n",np.setdiff1d(a,b))
print("Operación xor simétrica (filas en a o b pero no en ambos):\n",np.setxor1d(a,b))


Array a:
 [[1 2]
 [3 4]
 [5 6]]
Array b:
 [[3 4]
 [5 6]
 [7 8]]
Unión de a y b:
 [1 2 3 4 5 6 7 8]
Intersección de a y b:
 [3 4 5 6]
Diferencia de a y b (filas en a no en b):
 [1 2]
Operación xor simétrica (filas en a o b pero no en ambos):
 [1 2 7 8]


In [31]:
a = np.array([4,8,4,7,2,5,1])
print("Array a:\n",a)
a.sort()
print("Array a ordenado:\n",a)

Array a:
 [4 8 4 7 2 5 1]
Array a ordenado:
 [1 2 4 4 5 7 8]


In [34]:
a = np.array([4,8,4,7,2,5,1])
print("Array a ordenado:\n",a)
i = a.argsort()
print("Array de índices para ordenar a:\n",i)
print("Array a ordenado usando los índices:\n",a[i])

Array a ordenado:
 [4 8 4 7 2 5 1]
Array de índices para ordenar a:
 [6 4 0 2 5 3 1]
Array a ordenado usando los índices:
 [1 2 4 4 5 7 8]


In [37]:
a = np.array([[6,8,4],
              [3,2,7],
              [9,3,1]])
print("Array a:\n",a)
b = a.copy() # copia para no perder los datos originales
b.sort()
print("Array b ordenado tal cual (ordena por filas)",b)
b = a.copy()
print("Array b ordenado por columnas (axis=0):\n",np.sort(b,axis=0))

Array a:
 [[6 8 4]
 [3 2 7]
 [9 3 1]]
Array b ordenado tal cual (ordena por filas) [[4 6 8]
 [2 3 7]
 [1 3 9]]
Array b ordenado por columnas (axis=0):
 [[3 2 1]
 [6 3 4]
 [9 8 7]]
